global:
  scrape_interval: 15s

scrape_configs:
  # 1. Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # 2. Scrape node_exporter (optional)
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]